Repository primihub/primihub, pull requests merged in 2022-07, with the labels that each got.

#46 [hotfix] readme create task hyperlink
  README.md
  README_CN.md
Labels: documentation

#60 [feat] auto compute plain mod bit size to fit db size
  src/primihub/task/semantic/pir_client_task.cc
  src/primihub/task/semantic/pir_client_task.h
  src/primihub/task/semantic/pir_server_task.cc
  src/primihub/task/semantic/pir_server_task.h
Labels: enhancement

#58 [fix] load db from leveldb dump
  config/node2.yaml
  src/primihub/node/node.cc
  src/primihub/node/node.h
  src/primihub/node/nodelet.cc
  src/primihub/service/dataset/localkv/storage_leveldb.cc
  src/primihub/service/dataset/localkv/storage_leveldb.h
  src/primihub/service/dataset/service.cc
  src/primihub/service/dataset/util.hpp
Labels: bug
